apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx-deployment
  namespace: namespace4

spec:
  syncPolicy:
    managedNamespaceMetadata:
      annotations:
        abc: 123 # adding this is informational with SSA; this would be sticking around in any case until we set a new value
    syncOptions:
      - CreateNamespace=true
  selector:

    matchLabels:

      app: nginx

  replicas: 1 # tells deployment to run 2 pods matching the template

  template:

    metadata:

      labels:

        app: nginx

    spec:

      containers:

      - name: nginx

        image: nginx:1.14.2

        ports:

        - containerPort: 80

